apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  namespace: tech-challenge
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "tech-challenge-api"
  Jwt__Audience: "tech-challenge-api"
  CLOUD_SQL_CONNECTION_NAME: "vcosta-fiap-tech-challenge:us-central1:tech-challenge-pg"
