apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: tech-challenge
  annotations:
    iam.gke.io/gcp-service-account: tech-challenge-api@vcosta-fiap-tech-challenge.iam.gserviceaccount.com
